/*
 * Sidebar
 *
 * One sidebar, five sections, authored by hand rather than autogenerated so
 * the reading order is deliberate: install, then configure, then the features,
 * then multi-agent dispatch, then the flat reference material you look things
 * up in.
 *
 * @joestump-agent 08/25/2026 - Initial sidebar for the MVP docs site.
 *
 * @joestump-agent 08/25/2026 - Added the "What this fork adds" page directly
 * under the introduction, so the fork inventory is the second thing a reader
 * sees rather than something they have to hunt for.
 *
 * @joestump-agent 10/04/2026 - Added the "Multi-agent" category between
 * Features and Reference for the dispatch / A2A pages, ordered from the
 * overview and tutorial through configuration to the architecture, protocol,
 * troubleshooting and design-decision pages.
 */

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'introduction',
    'fork',
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/quickstart',
        'getting-started/providers-and-api-keys',
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      collapsed: false,
      items: [
        'configuration/crushrc',
        'configuration/command-reference',
        'configuration/json',
        'configuration/providers',
        'configuration/permissions',
        'configuration/context-and-ignore',
        'configuration/environment',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      collapsed: false,
      items: [
        'features/lsp',
        'features/mcp',
        'features/channels',
        'features/a2ui',
        'features/skills',
        'features/hooks',
        'features/scheduled-tasks',
        'features/semantic-search',
        'features/sessions',
        'features/server-and-workspaces',
        'features/notifications',
      ],
    },
    {
      type: 'category',
      label: 'Multi-agent',
      collapsed: false,
      items: [
        'agents/overview',
        'agents/tutorial',
        'agents/handles-and-inspect',
        'agents/todo-enforcement',
        'agents/configuration',
        'agents/architecture',
        'agents/a2a-protocol',
        'agents/troubleshooting',
        'agents/design-decisions',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        'reference/cli',
        'reference/tools',
        'reference/keybindings',
        'reference/environment-variables',
        'reference/logging',
        'reference/troubleshooting',
      ],
    },
  ],
};

export default sidebars;
