/*
 * Sidebar
 *
 * One sidebar, four sections, authored by hand rather than autogenerated so
 * the reading order is deliberate: install, then configure, then the features,
 * then the flat reference material you look things up in.
 *
 * @joestump-agent 08/25/2026 - Initial sidebar for the MVP docs site.
 */

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'introduction',
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/quickstart',
        'getting-started/providers-and-api-keys',
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      collapsed: false,
      items: [
        'configuration/crushrc',
        'configuration/command-reference',
        'configuration/json',
        'configuration/providers',
        'configuration/permissions',
        'configuration/context-and-ignore',
        'configuration/environment',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      collapsed: false,
      items: [
        'features/lsp',
        'features/mcp',
        'features/channels',
        'features/a2ui',
        'features/sidekick',
        'features/skills',
        'features/hooks',
        'features/scheduled-tasks',
        'features/semantic-search',
        'features/sessions',
        'features/server-and-workspaces',
        'features/notifications',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        'reference/cli',
        'reference/tools',
        'reference/keybindings',
        'reference/environment-variables',
        'reference/logging',
        'reference/troubleshooting',
      ],
    },
  ],
};

export default sidebars;
