// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: a2a_tasks.sql

package db

import (
	"context"
)

const countA2ATasks = `-- name: CountA2ATasks :one
SELECT count(*) FROM a2a_tasks
WHERE "user" = ?1
  AND (?2 = '' OR context_id = ?2)
  AND (?3 = '' OR state = ?3)
  AND (?4 = 0 OR updated_at >= ?4)
`

type CountA2ATasksParams struct {
	User      string      `json:"user"`
	ContextID interface{} `json:"context_id"`
	State     interface{} `json:"state"`
	After     interface{} `json:"after"`
}

func (q *Queries) CountA2ATasks(ctx context.Context, arg CountA2ATasksParams) (int64, error) {
	row := q.queryRow(ctx, q.countA2ATasksStmt, countA2ATasks,
		arg.User,
		arg.ContextID,
		arg.State,
		arg.After,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createA2ATask = `-- name: CreateA2ATask :exec
INSERT INTO a2a_tasks (
    id,
    context_id,
    "user",
    host_id,
    state,
    version,
    task_json,
    created_at,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    1,
    ?6,
    ?7,
    ?8
)
`

type CreateA2ATaskParams struct {
	ID        string `json:"id"`
	ContextID string `json:"context_id"`
	User      string `json:"user"`
	HostID    string `json:"host_id"`
	State     string `json:"state"`
	TaskJson  string `json:"task_json"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) CreateA2ATask(ctx context.Context, arg CreateA2ATaskParams) error {
	_, err := q.exec(ctx, q.createA2ATaskStmt, createA2ATask,
		arg.ID,
		arg.ContextID,
		arg.User,
		arg.HostID,
		arg.State,
		arg.TaskJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getA2ATask = `-- name: GetA2ATask :one
SELECT id, context_id, user, host_id, state, version, task_json, created_at, updated_at FROM a2a_tasks
WHERE id = ?1
LIMIT 1
`

func (q *Queries) GetA2ATask(ctx context.Context, id string) (A2aTask, error) {
	row := q.queryRow(ctx, q.getA2ATaskStmt, getA2ATask, id)
	var i A2aTask
	err := row.Scan(
		&i.ID,
		&i.ContextID,
		&i.User,
		&i.HostID,
		&i.State,
		&i.Version,
		&i.TaskJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listA2ATasks = `-- name: ListA2ATasks :many
SELECT id, context_id, user, host_id, state, version, task_json, created_at, updated_at FROM a2a_tasks
WHERE "user" = ?1
  AND (?2 = '' OR context_id = ?2)
  AND (?3 = '' OR state = ?3)
  AND (?4 = 0 OR updated_at >= ?4)
  AND (?5 = 0 OR updated_at < ?5 OR (updated_at = ?5 AND id < ?6))
ORDER BY updated_at DESC, id DESC
LIMIT ?7
`

type ListA2ATasksParams struct {
	User      string      `json:"user"`
	ContextID interface{} `json:"context_id"`
	State     interface{} `json:"state"`
	After     interface{} `json:"after"`
	CursorAt  interface{} `json:"cursor_at"`
	CursorID  string      `json:"cursor_id"`
	PageSize  int64       `json:"page_size"`
}

func (q *Queries) ListA2ATasks(ctx context.Context, arg ListA2ATasksParams) ([]A2aTask, error) {
	rows, err := q.query(ctx, q.listA2ATasksStmt, listA2ATasks,
		arg.User,
		arg.ContextID,
		arg.State,
		arg.After,
		arg.CursorAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []A2aTask{}
	for rows.Next() {
		var i A2aTask
		if err := rows.Scan(
			&i.ID,
			&i.ContextID,
			&i.User,
			&i.HostID,
			&i.State,
			&i.Version,
			&i.TaskJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateA2ATask = `-- name: UpdateA2ATask :execrows
UPDATE a2a_tasks SET
    context_id = ?1,
    state = ?2,
    version = version + 1,
    task_json = ?3,
    updated_at = ?4
WHERE id = ?5
`

type UpdateA2ATaskParams struct {
	ContextID string `json:"context_id"`
	State     string `json:"state"`
	TaskJson  string `json:"task_json"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateA2ATask(ctx context.Context, arg UpdateA2ATaskParams) (int64, error) {
	result, err := q.exec(ctx, q.updateA2ATaskStmt, updateA2ATask,
		arg.ContextID,
		arg.State,
		arg.TaskJson,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateA2ATaskIfVersion = `-- name: UpdateA2ATaskIfVersion :execrows
UPDATE a2a_tasks SET
    context_id = ?1,
    state = ?2,
    version = version + 1,
    task_json = ?3,
    updated_at = ?4
WHERE id = ?5 AND version = ?6
`

type UpdateA2ATaskIfVersionParams struct {
	ContextID string `json:"context_id"`
	State     string `json:"state"`
	TaskJson  string `json:"task_json"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
	Version   int64  `json:"version"`
}

func (q *Queries) UpdateA2ATaskIfVersion(ctx context.Context, arg UpdateA2ATaskIfVersionParams) (int64, error) {
	result, err := q.exec(ctx, q.updateA2ATaskIfVersionStmt, updateA2ATaskIfVersion,
		arg.ContextID,
		arg.State,
		arg.TaskJson,
		arg.UpdatedAt,
		arg.ID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
