// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: a2a_dispatches.sql

package db

import (
	"context"
)

const failA2ADispatch = `-- name: FailA2ADispatch :execrows
UPDATE a2a_dispatches SET
    status = 'failed',
    result_json = ?1,
    updated_at = ?2
WHERE dispatch_id = ?3 AND status = 'running'
`

type FailA2ADispatchParams struct {
	ResultJson string `json:"result_json"`
	UpdatedAt  int64  `json:"updated_at"`
	DispatchID string `json:"dispatch_id"`
}

func (q *Queries) FailA2ADispatch(ctx context.Context, arg FailA2ADispatchParams) (int64, error) {
	result, err := q.exec(ctx, q.failA2ADispatchStmt, failA2ADispatch, arg.ResultJson, arg.UpdatedAt, arg.DispatchID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishA2ADispatch = `-- name: FinishA2ADispatch :execrows
UPDATE a2a_dispatches SET
    status = ?1,
    result_json = ?2,
    updated_at = ?3
WHERE dispatch_id = ?4 AND status = 'running'
`

type FinishA2ADispatchParams struct {
	Status     string `json:"status"`
	ResultJson string `json:"result_json"`
	UpdatedAt  int64  `json:"updated_at"`
	DispatchID string `json:"dispatch_id"`
}

func (q *Queries) FinishA2ADispatch(ctx context.Context, arg FinishA2ADispatchParams) (int64, error) {
	result, err := q.exec(ctx, q.finishA2ADispatchStmt, finishA2ADispatch,
		arg.Status,
		arg.ResultJson,
		arg.UpdatedAt,
		arg.DispatchID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getA2ADispatch = `-- name: GetA2ADispatch :one
SELECT dispatch_id, task_id, session_id, parent_session_id, handle, branch, workspace_path, status, result_json, delivered_at, host_id, updated_at FROM a2a_dispatches
WHERE dispatch_id = ?1
LIMIT 1
`

func (q *Queries) GetA2ADispatch(ctx context.Context, dispatchID string) (A2aDispatch, error) {
	row := q.queryRow(ctx, q.getA2ADispatchStmt, getA2ADispatch, dispatchID)
	var i A2aDispatch
	err := row.Scan(
		&i.DispatchID,
		&i.TaskID,
		&i.SessionID,
		&i.ParentSessionID,
		&i.Handle,
		&i.Branch,
		&i.WorkspacePath,
		&i.Status,
		&i.ResultJson,
		&i.DeliveredAt,
		&i.HostID,
		&i.UpdatedAt,
	)
	return i, err
}

const getA2ADispatchBySession = `-- name: GetA2ADispatchBySession :one
SELECT dispatch_id, task_id, session_id, parent_session_id, handle, branch, workspace_path, status, result_json, delivered_at, host_id, updated_at FROM a2a_dispatches
WHERE session_id = ?1
LIMIT 1
`

func (q *Queries) GetA2ADispatchBySession(ctx context.Context, sessionID string) (A2aDispatch, error) {
	row := q.queryRow(ctx, q.getA2ADispatchBySessionStmt, getA2ADispatchBySession, sessionID)
	var i A2aDispatch
	err := row.Scan(
		&i.DispatchID,
		&i.TaskID,
		&i.SessionID,
		&i.ParentSessionID,
		&i.Handle,
		&i.Branch,
		&i.WorkspacePath,
		&i.Status,
		&i.ResultJson,
		&i.DeliveredAt,
		&i.HostID,
		&i.UpdatedAt,
	)
	return i, err
}

const listNonTerminalA2ADispatches = `-- name: ListNonTerminalA2ADispatches :many
SELECT dispatch_id, task_id, session_id, parent_session_id, handle, branch, workspace_path, status, result_json, delivered_at, host_id, updated_at FROM a2a_dispatches
WHERE status = 'running'
ORDER BY updated_at
`

func (q *Queries) ListNonTerminalA2ADispatches(ctx context.Context) ([]A2aDispatch, error) {
	rows, err := q.query(ctx, q.listNonTerminalA2ADispatchesStmt, listNonTerminalA2ADispatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []A2aDispatch{}
	for rows.Next() {
		var i A2aDispatch
		if err := rows.Scan(
			&i.DispatchID,
			&i.TaskID,
			&i.SessionID,
			&i.ParentSessionID,
			&i.Handle,
			&i.Branch,
			&i.WorkspacePath,
			&i.Status,
			&i.ResultJson,
			&i.DeliveredAt,
			&i.HostID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNonTerminalA2ATasks = `-- name: ListNonTerminalA2ATasks :many
SELECT id, context_id, user, host_id, state, version, task_json, created_at, updated_at FROM a2a_tasks
WHERE state NOT IN ('TASK_STATE_COMPLETED', 'TASK_STATE_FAILED', 'TASK_STATE_CANCELED', 'TASK_STATE_REJECTED')
ORDER BY updated_at
`

func (q *Queries) ListNonTerminalA2ATasks(ctx context.Context) ([]A2aTask, error) {
	rows, err := q.query(ctx, q.listNonTerminalA2ATasksStmt, listNonTerminalA2ATasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []A2aTask{}
	for rows.Next() {
		var i A2aTask
		if err := rows.Scan(
			&i.ID,
			&i.ContextID,
			&i.User,
			&i.HostID,
			&i.State,
			&i.Version,
			&i.TaskJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUndeliveredA2ADispatches = `-- name: ListUndeliveredA2ADispatches :many
SELECT dispatch_id, task_id, session_id, parent_session_id, handle, branch, workspace_path, status, result_json, delivered_at, host_id, updated_at FROM a2a_dispatches
WHERE status IN ('completed', 'failed', 'killed')
  AND delivered_at = 0
ORDER BY updated_at
`

func (q *Queries) ListUndeliveredA2ADispatches(ctx context.Context) ([]A2aDispatch, error) {
	rows, err := q.query(ctx, q.listUndeliveredA2ADispatchesStmt, listUndeliveredA2ADispatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []A2aDispatch{}
	for rows.Next() {
		var i A2aDispatch
		if err := rows.Scan(
			&i.DispatchID,
			&i.TaskID,
			&i.SessionID,
			&i.ParentSessionID,
			&i.Handle,
			&i.Branch,
			&i.WorkspacePath,
			&i.Status,
			&i.ResultJson,
			&i.DeliveredAt,
			&i.HostID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markA2ADispatchDelivered = `-- name: MarkA2ADispatchDelivered :exec
UPDATE a2a_dispatches SET
    delivered_at = ?1,
    updated_at = ?1
WHERE dispatch_id = ?2
`

type MarkA2ADispatchDeliveredParams struct {
	DeliveredAt int64  `json:"delivered_at"`
	DispatchID  string `json:"dispatch_id"`
}

func (q *Queries) MarkA2ADispatchDelivered(ctx context.Context, arg MarkA2ADispatchDeliveredParams) error {
	_, err := q.exec(ctx, q.markA2ADispatchDeliveredStmt, markA2ADispatchDelivered, arg.DeliveredAt, arg.DispatchID)
	return err
}

const setA2ADispatchTask = `-- name: SetA2ADispatchTask :exec
UPDATE a2a_dispatches SET
    task_id = ?1,
    updated_at = ?2
WHERE dispatch_id = ?3
`

type SetA2ADispatchTaskParams struct {
	TaskID     string `json:"task_id"`
	UpdatedAt  int64  `json:"updated_at"`
	DispatchID string `json:"dispatch_id"`
}

func (q *Queries) SetA2ADispatchTask(ctx context.Context, arg SetA2ADispatchTaskParams) error {
	_, err := q.exec(ctx, q.setA2ADispatchTaskStmt, setA2ADispatchTask, arg.TaskID, arg.UpdatedAt, arg.DispatchID)
	return err
}

const upsertA2ADispatch = `-- name: UpsertA2ADispatch :exec
INSERT INTO a2a_dispatches (
    dispatch_id,
    task_id,
    session_id,
    parent_session_id,
    handle,
    branch,
    workspace_path,
    status,
    result_json,
    delivered_at,
    host_id,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12
)
ON CONFLICT (dispatch_id) DO UPDATE SET
    task_id = excluded.task_id,
    session_id = excluded.session_id,
    parent_session_id = excluded.parent_session_id,
    handle = excluded.handle,
    branch = excluded.branch,
    workspace_path = excluded.workspace_path,
    status = excluded.status,
    result_json = excluded.result_json,
    delivered_at = excluded.delivered_at,
    host_id = excluded.host_id,
    updated_at = excluded.updated_at
`

type UpsertA2ADispatchParams struct {
	DispatchID      string `json:"dispatch_id"`
	TaskID          string `json:"task_id"`
	SessionID       string `json:"session_id"`
	ParentSessionID string `json:"parent_session_id"`
	Handle          string `json:"handle"`
	Branch          string `json:"branch"`
	WorkspacePath   string `json:"workspace_path"`
	Status          string `json:"status"`
	ResultJson      string `json:"result_json"`
	DeliveredAt     int64  `json:"delivered_at"`
	HostID          string `json:"host_id"`
	UpdatedAt       int64  `json:"updated_at"`
}

func (q *Queries) UpsertA2ADispatch(ctx context.Context, arg UpsertA2ADispatchParams) error {
	_, err := q.exec(ctx, q.upsertA2ADispatchStmt, upsertA2ADispatch,
		arg.DispatchID,
		arg.TaskID,
		arg.SessionID,
		arg.ParentSessionID,
		arg.Handle,
		arg.Branch,
		arg.WorkspacePath,
		arg.Status,
		arg.ResultJson,
		arg.DeliveredAt,
		arg.HostID,
		arg.UpdatedAt,
	)
	return err
}
