// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddSessionCost(ctx context.Context, arg AddSessionCostParams) error
	AddSessionUsage(ctx context.Context, arg AddSessionUsageParams) error
	CountA2ATasks(ctx context.Context, arg CountA2ATasksParams) (int64, error)
	CreateA2ATask(ctx context.Context, arg CreateA2ATaskParams) error
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteFile(ctx context.Context, id string) error
	DeleteMCPDisabledServer(ctx context.Context, name string) error
	DeleteMCPEnabledServer(ctx context.Context, name string) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionFiles(ctx context.Context, sessionID string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	FailA2ADispatch(ctx context.Context, arg FailA2ADispatchParams) (int64, error)
	FinishA2ADispatch(ctx context.Context, arg FinishA2ADispatchParams) (int64, error)
	GetA2ADispatch(ctx context.Context, dispatchID string) (A2aDispatch, error)
	GetA2ADispatchBySession(ctx context.Context, sessionID string) (A2aDispatch, error)
	GetA2ATask(ctx context.Context, id string) (A2aTask, error)
	GetAverageResponseTime(ctx context.Context) (int64, error)
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetFileRead(ctx context.Context, arg GetFileReadParams) (ReadFile, error)
	GetHourDayHeatmap(ctx context.Context) ([]GetHourDayHeatmapRow, error)
	GetLastAssistantMessageBySession(ctx context.Context, sessionID string) (Message, error)
	GetLastSession(ctx context.Context) (Session, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetRecentActivity(ctx context.Context) ([]GetRecentActivityRow, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetToolUsage(ctx context.Context) ([]GetToolUsageRow, error)
	GetTotalStats(ctx context.Context) (GetTotalStatsRow, error)
	GetUsageByDay(ctx context.Context) ([]GetUsageByDayRow, error)
	GetUsageByDayOfWeek(ctx context.Context) ([]GetUsageByDayOfWeekRow, error)
	GetUsageByHour(ctx context.Context) ([]GetUsageByHourRow, error)
	GetUsageByModel(ctx context.Context) ([]GetUsageByModelRow, error)
	InsertMCPDisabledServer(ctx context.Context, name string) error
	InsertMCPEnabledServer(ctx context.Context, name string) error
	ListA2ATasks(ctx context.Context, arg ListA2ATasksParams) ([]A2aTask, error)
	ListAllChildSessions(ctx context.Context) ([]Session, error)
	// Backs prompt history when no session is open. Needs
	// idx_messages_role_created_at to seek rather than scan the table.
	ListAllUserMessages(ctx context.Context) ([]Message, error)
	ListChildSessions(ctx context.Context, parentSessionID sql.NullString) ([]Session, error)
	ListFilesByPath(ctx context.Context, path string) ([]File, error)
	ListFilesBySession(ctx context.Context, sessionID string) ([]File, error)
	ListLatestSessionFiles(ctx context.Context, sessionID string) ([]File, error)
	ListMCPDisabledServers(ctx context.Context) ([]string, error)
	ListMCPEnabledServers(ctx context.Context) ([]string, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	// Messages from the summary onward, which is all a compacted session sends.
	// created_at has one-second resolution, so a few messages preceding the
	// summary can come back too; the caller slices from the summary by ID.
	ListMessagesBySessionFromSummary(ctx context.Context, arg ListMessagesBySessionFromSummaryParams) ([]Message, error)
	ListNewFiles(ctx context.Context) ([]File, error)
	ListNonTerminalA2ADispatches(ctx context.Context) ([]A2aDispatch, error)
	ListNonTerminalA2ATasks(ctx context.Context) ([]A2aTask, error)
	ListSessionReadFiles(ctx context.Context, sessionID string) ([]ReadFile, error)
	ListSessions(ctx context.Context) ([]Session, error)
	ListUndeliveredA2ADispatches(ctx context.Context) ([]A2aDispatch, error)
	// Backs prompt history, which steps back one entry at a time.
	ListUserMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	MarkA2ADispatchDelivered(ctx context.Context, arg MarkA2ADispatchDeliveredParams) error
	RecordFileRead(ctx context.Context, arg RecordFileReadParams) error
	RenameSession(ctx context.Context, arg RenameSessionParams) error
	SetA2ADispatchTask(ctx context.Context, arg SetA2ADispatchTaskParams) error
	SetSessionChannel(ctx context.Context, arg SetSessionChannelParams) (Session, error)
	UpdateA2ATask(ctx context.Context, arg UpdateA2ATaskParams) (int64, error)
	UpdateA2ATaskIfVersion(ctx context.Context, arg UpdateA2ATaskIfVersionParams) (int64, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateSessionTitleAndUsage(ctx context.Context, arg UpdateSessionTitleAndUsageParams) error
	UpsertA2ADispatch(ctx context.Context, arg UpsertA2ADispatchParams) error
}

var _ Querier = (*Queries)(nil)
